- hosts: mycomputer

  tasks:

  - name: create ami image
    amazon.aws.ec2_ami:
      instance_id: "{{ ec2_id }}"
      wait: yes
      name: '{{ ami_name }}'
      region: '{{ aws_region }}'
      tags:
        Name: '{{ ami_name }}'
        Service: ansible
    register: output

  - name: print output
    debug:
      var: output