---
# tasks file for installDocker

- apt_key: {state: present, url: 'https://download.docker.com/linux/debian/gpg'}
  name: add apt signing key from official docker repo

- apt_repository: {repo: 'deb [arch=amd64] https://download.docker.com/linux/debian
      stretch stable', state: present}
  name: add docker official repository for Debian Stretch

- apt: {force_apt_get: true, install_recommends: true, name: [docker-ce,apt-transport-https,ca-certificates,curl,software-properties-common], state: latest,
    update_cache: true}
  name: installing
  
- get_url: {dest: /usr/local/bin/docker-compose, mode: '0755', url: 'https://github.com/docker/compose/releases/download/1.25.4/docker-compose-Linux-x86_64'}
  name: installing docker-compose